/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/OuterWallGLTF/outer_wall_and_sheath-transformed.gltf -o src/Models/outerWall.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { type ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    polySurface1: THREE.Mesh
    polySurface10: THREE.Mesh
    polySurface100: THREE.Mesh
    polySurface101: THREE.Mesh
    polySurface102: THREE.Mesh
    polySurface103: THREE.Mesh
    polySurface104: THREE.Mesh
    polySurface105: THREE.Mesh
    polySurface106: THREE.Mesh
    polySurface107: THREE.Mesh
    polySurface108: THREE.Mesh
    polySurface109: THREE.Mesh
    polySurface11: THREE.Mesh
    polySurface110: THREE.Mesh
    polySurface111: THREE.Mesh
    polySurface112: THREE.Mesh
    polySurface113: THREE.Mesh
    polySurface12: THREE.Mesh
    polySurface13: THREE.Mesh
    polySurface14: THREE.Mesh
    polySurface15: THREE.Mesh
    polySurface16: THREE.Mesh
    polySurface17: THREE.Mesh
    polySurface18: THREE.Mesh
    polySurface19: THREE.Mesh
    polySurface2: THREE.Mesh
    polySurface20: THREE.Mesh
    polySurface21: THREE.Mesh
    polySurface22: THREE.Mesh
    polySurface23: THREE.Mesh
    polySurface24: THREE.Mesh
    polySurface25: THREE.Mesh
    polySurface26: THREE.Mesh
    polySurface27: THREE.Mesh
    polySurface28: THREE.Mesh
    polySurface29: THREE.Mesh
    polySurface3: THREE.Mesh
    polySurface30: THREE.Mesh
    polySurface31: THREE.Mesh
    polySurface32: THREE.Mesh
    polySurface33: THREE.Mesh
    polySurface34: THREE.Mesh
    polySurface35: THREE.Mesh
    polySurface36: THREE.Mesh
    polySurface37: THREE.Mesh
    polySurface38: THREE.Mesh
    polySurface39: THREE.Mesh
    polySurface4: THREE.Mesh
    polySurface40: THREE.Mesh
    polySurface41: THREE.Mesh
    polySurface42: THREE.Mesh
    polySurface43: THREE.Mesh
    polySurface44: THREE.Mesh
    polySurface45: THREE.Mesh
    polySurface46: THREE.Mesh
    polySurface47: THREE.Mesh
    polySurface48: THREE.Mesh
    polySurface49: THREE.Mesh
    polySurface5: THREE.Mesh
    polySurface50: THREE.Mesh
    polySurface51: THREE.Mesh
    polySurface52: THREE.Mesh
    polySurface53: THREE.Mesh
    polySurface54: THREE.Mesh
    polySurface55: THREE.Mesh
    polySurface56: THREE.Mesh
    polySurface57: THREE.Mesh
    polySurface58: THREE.Mesh
    polySurface59: THREE.Mesh
    polySurface6: THREE.Mesh
    polySurface60: THREE.Mesh
    polySurface61: THREE.Mesh
    polySurface62: THREE.Mesh
    polySurface63: THREE.Mesh
    polySurface64: THREE.Mesh
    polySurface65: THREE.Mesh
    polySurface66: THREE.Mesh
    polySurface67: THREE.Mesh
    polySurface68: THREE.Mesh
    polySurface69: THREE.Mesh
    polySurface7: THREE.Mesh
    polySurface70: THREE.Mesh
    polySurface71: THREE.Mesh
    polySurface72: THREE.Mesh
    polySurface73: THREE.Mesh
    polySurface74: THREE.Mesh
    polySurface75: THREE.Mesh
    polySurface76: THREE.Mesh
    polySurface77: THREE.Mesh
    polySurface78: THREE.Mesh
    polySurface79: THREE.Mesh
    polySurface8: THREE.Mesh
    polySurface80: THREE.Mesh
    polySurface81: THREE.Mesh
    polySurface82: THREE.Mesh
    polySurface83: THREE.Mesh
    polySurface84: THREE.Mesh
    polySurface85: THREE.Mesh
    polySurface86: THREE.Mesh
    polySurface87: THREE.Mesh
    polySurface88: THREE.Mesh
    polySurface89: THREE.Mesh
    polySurface9: THREE.Mesh
    polySurface90: THREE.Mesh
    polySurface91: THREE.Mesh
    polySurface92: THREE.Mesh
    polySurface93: THREE.Mesh
    polySurface94: THREE.Mesh
    polySurface95: THREE.Mesh
    polySurface96: THREE.Mesh
    polySurface97: THREE.Mesh
    polySurface98: THREE.Mesh
    polySurface99: THREE.Mesh
    polySurface114: THREE.Mesh
    polySurface115: THREE.Mesh
    polySurface116: THREE.Mesh
    polySurface117: THREE.Mesh
    polySurface118: THREE.Mesh
    polySurface119: THREE.Mesh
    polySurface120: THREE.Mesh
    polySurface121: THREE.Mesh
    polySurface122: THREE.Mesh
    polySurface123: THREE.Mesh
    polySurface124: THREE.Mesh
    polySurface125: THREE.Mesh
    polySurface126: THREE.Mesh
    polySurface127: THREE.Mesh
    polySurface128: THREE.Mesh
    polySurface129: THREE.Mesh
    polySurface130: THREE.Mesh
    polySurface131: THREE.Mesh
    polySurface132: THREE.Mesh
    polySurface133: THREE.Mesh
    polySurface134: THREE.Mesh
    polySurface135: THREE.Mesh
    polySurface136: THREE.Mesh
    polySurface137: THREE.Mesh
    polySurface138: THREE.Mesh
    polySurface139: THREE.Mesh
    polySurface140: THREE.Mesh
    polySurface141: THREE.Mesh
    polySurface142: THREE.Mesh
    polySurface143: THREE.Mesh
    polySurface144: THREE.Mesh
    polySurface145: THREE.Mesh
    polySurface146: THREE.Mesh
    polySurface147: THREE.Mesh
    polySurface148: THREE.Mesh
    polySurface149: THREE.Mesh
    polySurface150: THREE.Mesh
    polySurface151: THREE.Mesh
    polySurface152: THREE.Mesh
    polySurface153: THREE.Mesh
    polySurface154: THREE.Mesh
    polySurface155: THREE.Mesh
    polySurface156: THREE.Mesh
    polySurface157: THREE.Mesh
    Mesh: THREE.Mesh
    Sheath: THREE.Mesh
  }
  materials: {
    lambert8: THREE.MeshStandardMaterial
    calcium_channel1: THREE.MeshStandardMaterial
    lambert6: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    sheath: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}
export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/outer_wall_and_sheath-transformed.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.167, 0, -0.063]} rotation={[Math.PI / 2, 0, 0.118]} scale={0.01}>
        <mesh geometry={nodes.polySurface1.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface10.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface100.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface101.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface102.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface103.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface104.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface105.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface106.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface107.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface108.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface109.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface11.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface110.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface111.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface112.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface113.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface12.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface13.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface14.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface15.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface16.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface17.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface18.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface19.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface2.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface20.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface21.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface22.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface23.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface24.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface25.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface26.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface27.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface28.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface29.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface3.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface30.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface31.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface32.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface33.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface34.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface35.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface36.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface37.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface38.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface39.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface4.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface40.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface41.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface42.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface43.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface44.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface45.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface46.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface47.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface48.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface49.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface5.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface50.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface51.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface52.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface53.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface54.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface55.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface56.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface57.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface58.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface59.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface6.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface60.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface61.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface62.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface63.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface64.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface65.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface66.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface67.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface68.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface69.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface7.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface70.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface71.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface72.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface73.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface74.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface75.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface76.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface77.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface78.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface79.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface8.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface80.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface81.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface82.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface83.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface84.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface85.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface86.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface87.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface88.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface89.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface9.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface90.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface91.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface92.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface93.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface94.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface95.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface96.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface97.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface98.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface99.geometry} material={materials.lambert8} />
      </group>
      <group position={[0.167, 0, -0.063]} rotation={[Math.PI / 2, 0, 0.118]} scale={0.01}>
        <mesh geometry={nodes.polySurface114.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface115.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface116.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface117.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface118.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface119.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface120.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface121.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface122.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface123.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface124.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface125.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface126.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface127.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface128.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface129.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface130.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface131.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface132.geometry} material={materials.calcium_channel1} />
        <mesh geometry={nodes.polySurface133.geometry} material={materials.calcium_channel1} />
      </group>
      <group position={[0.167, 0, -0.063]} rotation={[Math.PI / 2, 0, 0.118]} scale={0.01}>
        <mesh geometry={nodes.polySurface134.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface135.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface136.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface137.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface138.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface139.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface140.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface141.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface142.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface143.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface144.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface145.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface146.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface147.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface148.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface149.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface150.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface151.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface152.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface153.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface154.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface155.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface156.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface157.geometry} material={materials.lambert6} />
      </group>
      <mesh geometry={nodes.Mesh.geometry} material={materials.lambert1} position={[0.167, 0, -0.063]} rotation={[Math.PI / 2, 0, 0.118]} scale={0.01} />
      <mesh geometry={nodes.Sheath.geometry} material={materials.sheath} position={[1.313, -0.115, -0.02]} rotation={[Math.PI / 2, 0, 0.119]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/outer_wall_and_sheath-transformed.gltf')
